# Generated by Django 4.2.25 on 2025-11-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wastes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste",
            name="coffe_waste",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="waste",
            name="food_cooked_waste",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="waste",
            name="student_waste",
            field=models.IntegerField(null=True),
        ),
    ]
