# Generated by Django 4.2.25 on 2025-11-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0002_hostel_students_count"),
        ("wastes", "0002_alter_waste_coffe_waste_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waste",
            name="students_present",
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("students_present", models.IntegerField()),
                ("students_absent", models.IntegerField()),
                (
                    "hostel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="hostels.hostel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="waste",
            name="attendaces",
            field=models.ManyToManyField(
                related_name="attendences", to="wastes.attendance"
            ),
        ),
    ]
