# Generated by Django 4.2.25 on 2025-11-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wastes", "0003_remove_waste_students_present_attendance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waste",
            old_name="attendaces",
            new_name="attendances",
        ),
    ]
