# Generated by Django 4.2.25 on 2025-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wastes", "0004_rename_attendaces_waste_attendances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste",
            name="attendances",
            field=models.ManyToManyField(
                related_name="attendances", to="wastes.attendance"
            ),
        ),
    ]
