# Generated by Django 4.2.25 on 2025-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("WARDEN", "WARDEN"),
                    ("FLOOR WARDEN", "WARDEN"),
                    ("USER", "User"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
