# Generated by Django 4.2.25 on 2025-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="dasd", max_length=50),
            preserve_default=False,
        ),
    ]
