# Generated by Django 4.2.25 on 2025-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fcm_token",
            field=models.TextField(max_length=240, null=True),
        ),
    ]
