# Generated by Django 5.2.7 on 2025-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
