# Generated by Django 4.2.25 on 2025-10-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
