# Generated by Django 4.2.25 on 2025-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="students_count",
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
