# Generated by Django 5.2.7 on 2025-10-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_hostell"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="hostell",
            new_name="hostel",
        ),
    ]
